namespace: kubeguard-dev
replicaCount: 1
image:
  repository: kubeguardcr.azurecr.io/notification-service
  tag: "12badabd9b14"
  pullPolicy: Always
service:
  port: 3004
  targetPort: 3004
serviceAccount:
  name: notification-service-sa
  azureClientId: "7d6479f5-17ac-4f10-b320-307df612c987" # Replace with Managed Identity Client ID for dev
rollout:
  autoPromotionEnabled: true
  previewReplicaCount: 1
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
livenessProbe:
  path: /healthz
  initialDelaySeconds: 15
  periodSeconds: 20
  failureThreshold: 3
readinessProbe:
  path: /ready
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
