namespace: kubeguard-prod
replicaCount: 2
image:
  repository: kubeguardcr.azurecr.io/notification-service
  tag: "v1.1.0"
  pullPolicy: Always
service:
  port: 3004
  targetPort: 3004
serviceAccount:
  name: notification-service-sa
  azureClientId: "7d6479f5-17ac-4f10-b320-307df612c987" 
rollout:
  autoPromotionEnabled: false
  previewReplicaCount: 1
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
livenessProbe:
  path: /healthz
  initialDelaySeconds: 15
  periodSeconds: 20
  failureThreshold: 3
readinessProbe:
  path: /ready
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
