namespace: kubeguard-dev
replicaCount: 1
image:
  repository: kubeguardprodcr.azurecr.io/notification-service
  tag: "287c6ba60959"
  pullPolicy: Always
service:
  port: 3004
  targetPort: 3004
serviceAccount:
  name: notification-service-sa
  azureClientId: "9435c20e-eaed-4e98-98ea-3512aa93d244"
keyVault:
  name: kubeguard-prod-kv
  tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
  secretPrefix: DEV-NOTIFICATION
rollout:
  autoPromotionEnabled: true
  previewReplicaCount: 1
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
livenessProbe:
  path: /healthz
  initialDelaySeconds: 15
  periodSeconds: 20
  failureThreshold: 3
readinessProbe:
  path: /ready
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
