replicaCount: 2
image:
  repository: kubeguardcr.azurecr.io/project-service
  pullPolicy: Always
  tag: "v1.1.0"
namespace: kubeguard-prod
service:
  type: ClusterIP
  port: 3001
  targetPort: 3001
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
serviceAccount:
  name: project-service-sa
  azureClientId: "7d6479f5-17ac-4f10-b320-307df612c987"
rollout:
  autoPromotionEnabled: false
  previewReplicaCount: 1
probes:
  liveness:
    path: /healthz
    port: 3001
    initialDelaySeconds: 15
    periodSeconds: 20
    failureThreshold: 3
  readiness:
    path: /ready
    port: 3001
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
