apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KubeGuardd/kubeguard-helm.git
    targetRevision: dev
    path: gateway
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeguard-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true