namespace: kubeguard-dev
replicaCount: 1
image:
  repository: kubeguardprodcr.azurecr.io/gateway
  tag: "021a8f402274"
  pullPolicy: IfNotPresent
containerPort: 3000
service:
  type: ClusterIP
  port: 3000
serviceAccount:
  name: gateway-sa
  azureClientId: "9435c20e-eaed-4e98-98ea-3512aa93d244"
keyVault:
  name: "kubeguard-prod-kv"
  tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
keyVault:
  name: kubeguard-prod-kv
  tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
  secretPrefix: DEV-GATEWAY
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
  readiness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
rollout:
  autoPromotionEnabled: true
  scaleDownDelaySeconds: 30
