namespace: kubeguard-prod
replicaCount: 2
image:
  repository: kubeguardcr.azurecr.io/gateway
  tag: "v1.1.0"
  pullPolicy: IfNotPresent
containerPort: 3000
service:
  type: ClusterIP
  port: 3000
serviceAccount:
  name: gateway-sa
  azureClientId: "00000000-0000-0000-0000-000000000000"
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
  readiness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
rollout:
  autoPromotionEnabled: false
  scaleDownDelaySeconds: 300
