apiVersion: v1
kind: Service
metadata:
  name: analysis-service-active
  namespace: {{ .Values.namespace }}
  labels:
    app: analysis-service
    role: active
    app.kubernetes.io/name: analysis-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: analysis-service
    rollouts-pod-template-hash: active
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: analysis-service-preview
  namespace: {{ .Values.namespace }}
  labels:
    app: analysis-service
    role: preview
    app.kubernetes.io/name: analysis-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: analysis-service
    rollouts-pod-template-hash: preview
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}