apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: project-service-kv-provider
  namespace: {{ .Values.namespace }}
spec:
  provider: azure

  secretObjects:
    - secretName: project-service-kv-secret
      type: Opaque
      data:
        - objectName: {{ .Values.keyVault.secretPrefix }}-NODE-ENV
          key: NODE_ENV
        - objectName: {{ .Values.keyVault.secretPrefix }}-PROJECT-PORT
          key: PROJECT_PORT
        - objectName: {{ .Values.keyVault.secretPrefix }}-MONGODB-URI
          key: MONGODB_URI
        - objectName: {{ .Values.keyVault.secretPrefix }}-INTERNAL-SECRET
          key: INTERNAL_SECRET
        - objectName: {{ .Values.keyVault.secretPrefix }}-ENCRYPTION-KEY
          key: ENCRYPTION_KEY
        - objectName: {{ .Values.keyVault.secretPrefix }}-GITHUB-TOKEN
          key: GITHUB_TOKEN
        - objectName: {{ .Values.keyVault.secretPrefix }}-GATEWAY-PUBLIC-URL
          key: GATEWAY_PUBLIC_URL
        - objectName: {{ .Values.keyVault.secretPrefix }}-WATCHER-SERVICE-URL
          key: WATCHER_SERVICE_URL
        - objectName: {{ .Values.keyVault.secretPrefix }}-LOG-LEVEL
          key: LOG_LEVEL
        - objectName: {{ .Values.keyVault.secretPrefix }}-SERVICE-NAME
          key: SERVICE_NAME

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.serviceAccount.azureClientId | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    tenantId: {{ .Values.keyVault.tenantId | quote }}

    objects: |
      array:
        - |
          objectName: {{ .Values.keyVault.secretPrefix }}-NODE-ENV
          objectType: secret
        - |
          objectName: {{ .Values.keyVault.secretPrefix }}-PROJECT-PORT
          objectType: secret
        - |
          objectName: {{ .Values.keyVault.secretPrefix }}-MONGODB-URI
          objectType: secret
        - |
          objectName: {{ .Values.keyVault.secretPrefix }}-INTERNAL-SECRET
          objectType: secret
        - |
          objectName: {{ .Values.keyVault.secretPrefix }}-ENCRYPTION-KEY
          objectType: secret
        - |
          objectName: {{ .Values.keyVault.secretPrefix }}-GITHUB-TOKEN
          objectType: secret
        - |
          objectName: {{ .Values.keyVault.secretPrefix }}-GATEWAY-PUBLIC-URL
          objectType: secret
        - |
          objectName: {{ .Values.keyVault.secretPrefix }}-WATCHER-SERVICE-URL
          objectType: secret
        - |
          objectName: {{ .Values.keyVault.secretPrefix }}-LOG-LEVEL
          objectType: secret
        - |
          objectName: {{ .Values.keyVault.secretPrefix }}-SERVICE-NAME
          objectType: secret