apiVersion: v1
kind: Service
metadata:
  name: project-service-active
  namespace: {{ .Values.namespace }}
  labels:
    app: project-service
    app.kubernetes.io/managed-by: helm
spec:
  type: {{ .Values.service.type }}
  selector:
    app: project-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: project-service-preview
  namespace: {{ .Values.namespace }}
  labels:
    app: project-service
    app.kubernetes.io/managed-by: helm
spec:
  type: {{ .Values.service.type }}
  selector:
    app: project-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

---
apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: {{ .Values.namespace }}
  labels:
    app: project-service
spec:
  type: ClusterIP
  selector:
    app: project-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}