apiVersion: v1
kind: Service
metadata:
  name: frontend-active
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
    role: active
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-preview
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
    role: preview
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
---
# frontend/templates/service-lb.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80