apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: kubeguard-gateway
    app.kubernetes.io/managed-by: helm
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.clientId | quote }}